### PR TITLE
Add derivatives for WeightedTriangle

### PR DESCRIPTION
**Pull request by DanielVandH**
This PR adds support for derivatives of `WeightedTriangle`. Currently it only works for `a, b, c > 0` since that is where the recurrence holds. Would it better to `@assert` this in the functions for the time being, or just leave it?

### CODE REVIEW

**Comment by DanielVandH** [comment]
Those errors seem unrelated to this change. I don't actually see that error at all when running the tests locally either...

**Comment by dlfivefifty** [comment]
Right, this is something I changed fixing plotting. I’ll have to fix it

**Comment by dlfivefifty** [comment]
I think the failures are due to a bug in FastTransforms.

**Comment by dlfivefifty** [comment]
@MikaelSlevinsky do you know why its crashing on Mac OS?

**Pull request merged**
