### PR TITLE
Generalized Zernike

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by dlfivefifty** [comment]
@MikaelSlevinsky What exactly do you use for the normalized Jacobi polynomials in https://mikaelslevinsky.github.io/FastTransforms/transforms.html? Mine are off by a constant:
```julia
julia> a,b = 0.1, 0.2; Zn = Zernike(a,b)[:,Block.(Base.OneTo(3))];

julia> factorize(Zn) \ Zernike(a,b)[:,1]
3-blocked 6-element PseudoBlockArray{Float64,1}:
 0.9012504626108302
 ──────────────────
 0.0               
 0.0               
 ──────────────────
 0.0               
 0.0               
 0.0               

julia> factorize(Zn) \ Zernike(a,b)[:,2]
3-blocked 6-element PseudoBlockArray{Float64,1}:
 -6.601361734541943e-17 
 ───────────────────────
  0.9012504626108306    
 -5.933997156901466e-17 
 ───────────────────────
 -2.6485738638974872e-17
 -1.2853007219776957e-16
  1.1292182002512834e-16

julia> factorize(Zn) \ Zernike(a,b)[:,3]
3-blocked 6-element PseudoBlockArray{Float64,1}:
 -6.391973585514219e-17
 ──────────────────────
  8.117056157414587e-17
  0.9012504626108306   
 ──────────────────────
 -5.297147727794973e-17
  9.07887934892399e-17 
  5.785317630814742e-17
```

**Comment by dlfivefifty** [comment]
Nevermind forgot to change `2^(m+2)` to `2^(m+a+b+2)`.

**Comment by MikaelSlevinsky** [comment]
P.S. I'm using a `ZernikeWeight` of r^{2a+1} (1-r^2)^b so that when a = b = 0, it's the uniform Cartesian weight. https://mikaelslevinsky.github.io/FastTransforms/transforms.html#disk2cxf

**Comment by dlfivefifty** [comment]
your notion of weight is different to mine. I'm always thinking of these in Cartesian coordinates so its `dx * dy` OR `r dr dθ`, not just `dr dθ`

**Comment by MikaelSlevinsky** [comment]
Ok that’s fine, just wanted to double check.

**Pull request merged**
